### ISSUE TITLE
新立産業殿　パソコン仕立て

### ISSUE THREAD

**Issue by jms-fukuta** [jms-web/SRS.H#10]
新立産業
碧南本社　　３台
富士松工場　２台

１階の作業場に５台、入荷したのでOSのセットアップ、Windows Updateまでをやってほしい

**Comment by jms-funato** [comment]
**メーラーは現在使用しているソフトで再設定すること**
もしLiveメールが必要な場合は、Webでの配信は終了しているため
`\\jmssrv2\D\TOOL\liveEssentials2012\`にあるインストーラを使用する
