### ISSUE TITLE
新しいPC納入

### ISSUE THREAD

**Issue by jms-fukuta** [jms-web/SRS.H#4]
新規パソコンを２台導入
DELから入荷されたら、セットアップして納品する

- Officeライセンスは置き換え元から移行する
プロダクトキーを管理MSアカウントに登録し、そこからインストール
おそらく次のMSライセンスチェック処理後、置き換え元端末のライセンス認証が解除される
もしくは、置き換え元端末のプロダクトキーがその端末でしか使用されていなければ、
置き換え元端末も引き続き使用可能

**Comment by jms-funato** [comment]
### 6/29 追加作業
#### 粂さんPC 
サーバの共有フォルダをネットワークドライブに割り当て

#### 飯野さんPC
ファイルをDドライブに移行したが、Accessリンクテーブルは旧環境(Cドライブ以下)を参照しているため、リンク先は変更せず、シンボリックリンクで旧環境のパスを作成
